# Generated by Django 3.2.9 on 2021-12-16 08:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8, unique=True)),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perishable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=1)),
                ('rtr_date', models.DateField(auto_now_add=True)),
                ('exp', models.DateField()),
            ],
        ),
    ]
