# Generated by Django 3.2.9 on 2021-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perishable',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
