# Generated by Django 3.2.9 on 2021-12-16 09:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_perishable_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='perishable',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
