# Generated by Django 3.2.9 on 2021-12-16 09:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211216_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
