# Generated by Django 3.2.9 on 2021-12-16 17:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211216_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='perishable',
            name='username',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AlterField(
            model_name='perishable',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='perishable',
            name='img_url',
            field=models.CharField(default=api.models.generate_unique_code, max_length=50),
        ),
    ]
