# Generated by Django 3.2.9 on 2021-12-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_perishable_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perishable',
            name='code',
        ),
    ]
