# Generated by Django 3.2.9 on 2021-12-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_perishable_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perishable',
            old_name='code',
            new_name='p_code',
        ),
    ]
