# Generated by Django 3.2.9 on 2021-12-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_code_perishable_p_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perishable',
            name='p_code',
        ),
    ]
