# Generated by Django 3.2.9 on 2021-12-21 13:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_perishable_p_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perishable',
            name='img_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='perishable',
            name='p_code',
            field=models.CharField(default=api.models.generate_unique_p_code, max_length=8, unique=True),
        ),
    ]
