# Generated by Django 3.2.9 on 2021-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211221_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perishable',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
