# Generated by Django 4.0 on 2022-01-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_perishable_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='perishable',
            name='b_code',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='perishable',
            name='categories',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='perishable',
            name='categories_score',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
