# Generated by Django 4.0 on 2022-01-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_perishable_b_code_perishable_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perishable',
            name='b_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='perishable',
            name='categories',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='perishable',
            name='categories_score',
            field=models.CharField(default='', max_length=200),
        ),
    ]
