# Generated by Django 3.2.9 on 2022-01-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_perishable_b_code_alter_perishable_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perishable',
            name='b_code',
            field=models.CharField(default='EMPTY', max_length=200),
        ),
        migrations.AlterField(
            model_name='perishable',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
