# Generated by Django 4.0.1 on 2022-03-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_perishable_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
